name:                switch-language
version:             0.1.0.0
github:              "lbuchli/switch-language"
license:             BSD3
author:              "Lukas Buchli"
maintainer:          "example@example.com"
copyright:           "2021 Lukas Buchli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Simple homoiconic dependently typed language
# category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lbuchli/switch-language#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  switch-language-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - switch-language

tests:
  switch-language-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - switch-language
